# Generated by Django 3.0 on 2020-09-25 08:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Std_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateTimeField()),
                ('age', models.IntegerField()),
                ('gender', models.IntegerField(choices=[(0, 'male'), (1, 'female')])),
                ('state', models.CharField(max_length=40)),
                ('city_street', models.CharField(max_length=100)),
                ('postal_code', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('secondary_rate', models.IntegerField()),
                ('mother_lunguage', models.CharField(max_length=40)),
                ('pyment_method', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('university_message', models.TextField(max_length=1000)),
            ],
        ),
    ]
